# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contactitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='publishedAt',
            field=models.DateTimeField(db_index=True, auto_now_add=True),
            preserve_default=True,
        ),
    ]
