# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160316_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendaitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='name',
            new_name='title',
        ),
    ]
