# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160316_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='url',
            new_name='documentUrl',
        ),
    ]
