# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20160317_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaitem',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-publishedAt']},
        ),
        migrations.AlterModelOptions(
            name='contactitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-publishedAt']},
        ),
    ]
