# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20160325_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('publishedAt', models.DateTimeField()),
                ('type', models.TextField(max_length=10)),
                ('body', models.TextField(null=True)),
                ('documentUrl', models.CharField(max_length=500, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
