# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('backend', '0008_timelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wants_push_notifications', models.BooleanField(default=False)),
                ('firebase_instance_id', models.CharField(max_length=256, null=True)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
